# Generated by Django 4.1.1 on 2022-10-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Prerequisite', models.CharField(max_length=255)),
                ('courseSkills', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('joinedCourses', models.CharField(choices=[('DS001D', 'DS001D'), ('UX001H ', 'UX001H '), ('y786J', 'y786J'), ('RG839R', 'RG839R')], max_length=20)),
                ('progress', models.CharField(choices=[('Attended', 'Attended'), ('Failed Interview', 'Failed Interview'), ('Not Invited ', 'Not Invited '), ('Passed Interview', 'Passed Interview'), ('Rejected', 'Rejected'), ('Criteria Not Met', 'Criteria Not Met')], max_length=20)),
                ('skills', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
            ],
        ),
    ]
