# Generated by Django 4.1.1 on 2022-10-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_APP', '0002_remove_course_id_alter_course_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
